openapi: 3.0.0
info:
  title: Newsignals.ai API
  description: |
    ## Obtain Your API Token
    You can receive a token here: [Get Token](https://docs.google.com/forms/d/1m9ueSol820pS9I5eifw58BOtwkX55cdCe3FWwh-jjvA/edit)
    
    ## API Overview
    This API retrieves the latest 10 news items along with associated tickers and probabilities. Each request returns the latest 10 news items in one response. 
    The request limit is 1 request per second.
    
    ## Code Examples
    Seek code examples in this [GitHub repository](https://github.com/ArtyomIgn/newsignals_api).
    
    ## Historical Data for Backtesting
    Get historical data for backtesting [here](https://discord.com/channels/1016026344154464347/1114231712495452170/1284247834937266297).
  version: "1.0.0"
servers:
  - url: https://oh.sssh.it
    description: Production server

paths:
  /news/free-signals:
    get:
      summary: Retrieve the latest 10 news signals
      description: |
        Fetches the latest 10 news items along with their tickers, probabilities, and timestamps. 
        Each request returns 10 items, with details including the time they were published and made available through the API.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A list of the latest 10 news items
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: array
                    items:
                      $ref: '#/components/schemas/NewsItem'
        '400':
          description: Bad request, possibly due to rate limit violation
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    NewsItem:
      type: object
      properties:
        tickers:
          type: string
          description: The stock tickers related to the news item
          example: "CVM"
        probability:
          type: string
          description: The probability associated with the news event
          example: "99"
        published_primary_source:
          type: string
          format: date-time
          description: Date and time when the news was first published
          example: "2024-09-16T11:30:00Z"
        available_through_api:
          type: string
          format: date-time
          description: Date and time when the news was made available through the API
          example: "2024-09-16T11:30:24.694Z"

externalDocs:
  description: Find out how to get a token
  url: https://docs.google.com/forms/d/1m9ueSol820pS9I5eifw58BOtwkX55cdCe3FWwh-jjvA/edit
